background           = 0a0a0a
foreground           = eeeeee
cursor-color         = eeeeee
selection-background = 6b6b6b
selection-foreground = eeeeee
palette = 0=#0a0a0a
palette = 1=#9b9b9b
palette = 2=#a7a7a7
palette = 3=#b3b3b3
palette = 4=#8f8f8f
palette = 5=#9b9b9b
palette = 6=#8f8f8f
palette = 7=#eeeeee
palette = 8=#6b6b6b
palette = 9=#b3b3b3
palette = 10=#bfbfbf
palette = 11=#cccccc
palette = 12=#b3b3b3
palette = 13=#bfbfbf
palette = 14=#b3b3b3
palette = 15=#ebebeb