format = """
$directory $git_branch$git_status$all
$character"""

add_newline = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold #ebebeb"
read_only = " RO"
read_only_style = "bold #9b9b9b"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "on [$branch]($style)"
style = "#838383"
symbol = ""

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "#b3b3b3"
conflicted = "!"
ahead = "+"
behind = "-"
diverged = "+-"
untracked = "?"
stashed = "*"
modified = "~"
staged = ">"
renamed = "r"
deleted = "x"

[character]
success_symbol = "[>](bold #a7a7a7)"
error_symbol = "[>](bold #9b9b9b)"
vimcmd_symbol = "[<](bold #eeeeee)"

[username]
format = "[$user]($style) "
style_user = "bold #ebebeb"
style_root = "bold #9b9b9b"
show_always = false

[hostname]
format = "[@$hostname]($style) "
style = "bold #838383"
ssh_only = true

[nodejs]
format = "[$symbol($version)]($style) "
symbol = "node "
style = "#838383"

[python]
format = "[$symbol$version]($style) "
symbol = "py "
style = "#838383"

[rust]
format = "[$symbol($version)]($style) "
symbol = "rs "
style = "#838383"

[golang]
format = "[$symbol($version)]($style) "
symbol = "go "
style = "#838383"

[java]
format = "[$symbol($version)]($style) "
symbol = "java "
style = "#838383"

[php]
format = "[$symbol($version)]($style) "
symbol = "php "
style = "#838383"

[ruby]
format = "[$symbol($version)]($style) "
symbol = "rb "
style = "#838383"

[nix_shell]
format = "[$symbol$state]($style) "
symbol = "nix "
style = "#838383"

[docker_context]
format = "[$symbol$context]($style) "
symbol = "docker "
style = "#838383"

[package]
format = "[$symbol$version]($style) "
symbol = "pkg "
style = "#838383"