# .config/lazygit/config.yml.template
gui:
  theme:
    activeBorderColor:
      - "eeeeee"
      - bold
    inactiveBorderColor:
      - "6b6b6b"
    searchingActiveBorderColor:
      - "8f8f8f"
    optionsTextColor:
      - "8f8f8f"
    selectedLineBgColor:
      - "131313"
    cherryPickedCommitFgColor:
      - "9b9b9b"
    cherryPickedCommitBgColor:
      - "8f8f8f"
    markedBaseCommitColor:
      - "b3b3b3"
    unstagedChangesColor:
      - "6b6b6b"     
    defaultFgColor:
      - "eeeeee"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    status:
      staged: "a7a7a7"  
      unstaged: "9b9b9b"
