# .config/lazygit/config.yml.template
gui:
  theme:
    activeBorderColor:
      - "ff6600"
      - bold
    inactiveBorderColor:
      - "732e00"
    searchingActiveBorderColor:
      - "607e1b"
    optionsTextColor:
      - "7e1b4d"
    selectedLineBgColor:
      - "140800"
    cherryPickedCommitFgColor:
      - "891d33"
    cherryPickedCommitBgColor:
      - "607e1b"
    markedBaseCommitColor:
      - "a3a31d"
    unstagedChangesColor:
      - "732e00"     
    defaultFgColor:
      - "ff6600"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    status:
      staged: "4d981b"  
      unstaged: "912115"
