$amber = rgba(eeeeeeff)
$amber_bright = rgba(ebebebff)
$amber_dim = rgba(6b6b6bff)
$amber_bg = rgba(181818ff)
$black = rgba(0a0a0aff)
$surface = rgba(131313ff)
$red = rgba(9b9b9bff)
$green = rgba(a7a7a7ff)
$yellow = rgba(b3b3b3ff)
$blue = rgba(8f8f8fff)