source = ~/.config/hypr/colors.conf

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    col.active_border = $amber
    col.inactive_border = $amber_dim
    layout = master
    resize_on_border = true
}

decoration {
    rounding = 0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }

    dim_inactive = true
    dim_strength = 0.2
}

animations {
    enabled = false
}

master {
    new_status = slave
    mfact = 0.55
}

dwindle {
    pseudotile = false
    preserve_split = true
    force_split = 2
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    focus_on_activate = true
    background_color = $black
}

cursor {
    no_hardware_cursors = true
    inactive_timeout = 3
    hide_on_key_press = true
}
