# Window Rules
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:title ^(File Operation Progress)$
windowrule = float on, match:title ^(Confirm)$
windowrule = float on, match:title ^(Open File)$
windowrule = float on, match:title ^(Save File)$
windowrule = float on, match:title ^(Volume Control)$
windowrule = center on, match:float true
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = size 480 270, match:title ^(Picture-in-Picture)$
windowrule = move 100%-490 100%-280, match:title ^(Picture-in-Picture)$
windowrule = float on, match:title ^(Library)$
windowrule = float on, match:class ^(scratchpad)$
windowrule = size 80% 80%, match:class ^(scratchpad)$
windowrule = center on, match:class ^(scratchpad)$
windowrule = stay_focused on, match:class ^(Rofi)$
windowrule = animation slide, match:class ^(Rofi)$
