vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "dynamic_theme"

local hl = vim.api.nvim_set_hl

local c = {
  base = "#ff6600",
  bright = "#ff9c59",
  dim = "#732e00",
  surface = "#140800",
  bg = "#1a0a00",
  black = "#0a0400",
  comment = "#703e1c",
  green = "#4d981b",
  green_bright = "#63c322",
  red = "#912115",
  red_bright = "#be2b1b",
  yellow = "#a3a31d",
  yellow_bright = "#cece24",
  blue = "#7e1b4d",
  blue_bright = "#a82466",
  magenta = "#891d33",
  magenta_bright = "#b32642",
  cyan = "#607e1b",
  cyan_bright = "#81a824",
}

hl(0, "Normal", { fg = c.base, bg = c.black })
hl(0, "NormalNC", { fg = c.base, bg = c.black })
hl(0, "NormalFloat", { fg = c.base, bg = c.black })
hl(0, "FloatBorder", { fg = c.dim, bg = c.black })
hl(0, "FloatTitle", { fg = c.bright, bg = c.black, bold = true })

hl(0, "Cursor", { fg = c.black, bg = c.base })
hl(0, "CursorLine", { bg = c.surface })
hl(0, "CursorColumn", { bg = c.surface })
hl(0, "CursorLineNr", { fg = c.bright, bold = true })
hl(0, "LineNr", { fg = c.dim })
hl(0, "SignColumn", { bg = c.black })
hl(0, "ColorColumn", { bg = c.surface })
hl(0, "VertSplit", { fg = c.dim })
hl(0, "WinSeparator", { fg = c.dim })

hl(0, "StatusLine", { fg = c.base, bg = c.surface })
hl(0, "StatusLineNC", { fg = c.dim, bg = c.black })
hl(0, "TabLine", { fg = c.dim, bg = c.black })
hl(0, "TabLineFill", { bg = c.black })
hl(0, "TabLineSel", { fg = c.bright, bg = c.surface, bold = true })

hl(0, "Pmenu", { fg = c.base, bg = c.surface })
hl(0, "PmenuSel", { fg = c.black, bg = c.base })
hl(0, "PmenuSbar", { bg = c.surface })
hl(0, "PmenuThumb", { bg = c.dim })

hl(0, "Visual", { bg = c.dim })
hl(0, "VisualNOS", { bg = c.dim })
hl(0, "Search", { fg = c.black, bg = c.yellow })
hl(0, "IncSearch", { fg = c.black, bg = c.yellow_bright })
hl(0, "CurSearch", { fg = c.black, bg = c.yellow_bright, bold = true })
hl(0, "Substitute", { fg = c.black, bg = c.red })

hl(0, "MatchParen", { fg = c.yellow_bright, bold = true, underline = true })
hl(0, "Folded", { fg = c.comment, bg = c.surface })
hl(0, "FoldColumn", { fg = c.dim })
hl(0, "NonText", { fg = c.dim })
hl(0, "SpecialKey", { fg = c.dim })
hl(0, "Whitespace", { fg = c.dim })
hl(0, "EndOfBuffer", { fg = c.black })

hl(0, "Directory", { fg = c.blue })
hl(0, "Title", { fg = c.bright, bold = true })
hl(0, "Question", { fg = c.green })
hl(0, "MoreMsg", { fg = c.green })
hl(0, "ModeMsg", { fg = c.base, bold = true })
hl(0, "WarningMsg", { fg = c.yellow })
hl(0, "ErrorMsg", { fg = c.red, bold = true })

hl(0, "SpellBad", { sp = c.red, undercurl = true })
hl(0, "SpellCap", { sp = c.yellow, undercurl = true })
hl(0, "SpellLocal", { sp = c.cyan, undercurl = true })
hl(0, "SpellRare", { sp = c.magenta, undercurl = true })

hl(0, "Comment", { fg = c.comment, italic = true })
hl(0, "Constant", { fg = c.bright })
hl(0, "String", { fg = c.green })
hl(0, "Character", { fg = c.green })
hl(0, "Number", { fg = c.magenta })
hl(0, "Boolean", { fg = c.magenta })
hl(0, "Float", { fg = c.magenta })
hl(0, "Identifier", { fg = c.base })
hl(0, "Function", { fg = c.bright })
hl(0, "Statement", { fg = c.bright, bold = true })
hl(0, "Conditional", { fg = c.bright, bold = true })
hl(0, "Repeat", { fg = c.bright, bold = true })
hl(0, "Label", { fg = c.cyan })
hl(0, "Operator", { fg = c.base })
hl(0, "Keyword", { fg = c.bright, bold = true })
hl(0, "Exception", { fg = c.red })
hl(0, "PreProc", { fg = c.cyan })
hl(0, "Include", { fg = c.cyan })
hl(0, "Define", { fg = c.cyan })
hl(0, "Macro", { fg = c.cyan })
hl(0, "PreCondit", { fg = c.cyan })
hl(0, "Type", { fg = c.yellow })
hl(0, "StorageClass", { fg = c.yellow })
hl(0, "Structure", { fg = c.yellow })
hl(0, "Typedef", { fg = c.yellow })
hl(0, "Special", { fg = c.bright })
hl(0, "SpecialChar", { fg = c.magenta })
hl(0, "Tag", { fg = c.bright })
hl(0, "Delimiter", { fg = c.base })
hl(0, "SpecialComment", { fg = c.comment, bold = true })
hl(0, "Debug", { fg = c.red })
hl(0, "Underlined", { underline = true })
hl(0, "Ignore", { fg = c.dim })
hl(0, "Error", { fg = c.red, bold = true })
hl(0, "Todo", { fg = c.black, bg = c.yellow, bold = true })

hl(0, "@variable", { fg = c.base })
hl(0, "@variable.builtin", { fg = c.red })
hl(0, "@variable.parameter", { fg = c.base, italic = true })
hl(0, "@variable.member", { fg = c.base })
hl(0, "@constant", { fg = c.bright })
hl(0, "@constant.builtin", { fg = c.magenta })
hl(0, "@constant.macro", { fg = c.magenta })
hl(0, "@module", { fg = c.base })
hl(0, "@label", { fg = c.cyan })
hl(0, "@string", { fg = c.green })
hl(0, "@string.documentation", { fg = c.green })
hl(0, "@string.regexp", { fg = c.cyan })
hl(0, "@string.escape", { fg = c.magenta })
hl(0, "@string.special", { fg = c.magenta })
hl(0, "@character", { fg = c.green })
hl(0, "@character.special", { fg = c.magenta })
hl(0, "@boolean", { fg = c.magenta })
hl(0, "@number", { fg = c.magenta })
hl(0, "@number.float", { fg = c.magenta })
hl(0, "@type", { fg = c.yellow })
hl(0, "@type.builtin", { fg = c.yellow })
hl(0, "@type.definition", { fg = c.yellow })
hl(0, "@type.qualifier", { fg = c.bright, bold = true })
hl(0, "@attribute", { fg = c.cyan })
hl(0, "@property", { fg = c.base })
hl(0, "@function", { fg = c.bright })
hl(0, "@function.builtin", { fg = c.bright })
hl(0, "@function.call", { fg = c.bright })
hl(0, "@function.macro", { fg = c.cyan })
hl(0, "@function.method", { fg = c.bright })
hl(0, "@function.method.call", { fg = c.bright })
hl(0, "@constructor", { fg = c.yellow })
hl(0, "@operator", { fg = c.base })
hl(0, "@keyword", { fg = c.bright, bold = true })
hl(0, "@keyword.coroutine", { fg = c.bright, bold = true })
hl(0, "@keyword.function", { fg = c.bright, bold = true })
hl(0, "@keyword.operator", { fg = c.bright })
hl(0, "@keyword.import", { fg = c.cyan })
hl(0, "@keyword.storage", { fg = c.bright, bold = true })
hl(0, "@keyword.repeat", { fg = c.bright, bold = true })
hl(0, "@keyword.return", { fg = c.bright, bold = true })
hl(0, "@keyword.debug", { fg = c.red })
hl(0, "@keyword.exception", { fg = c.red })
hl(0, "@keyword.conditional", { fg = c.bright, bold = true })
hl(0, "@keyword.directive", { fg = c.cyan })
hl(0, "@keyword.directive.define", { fg = c.cyan })
hl(0, "@punctuation.delimiter", { fg = c.dim })
hl(0, "@punctuation.bracket", { fg = c.dim })
hl(0, "@punctuation.special", { fg = c.cyan })
hl(0, "@comment", { fg = c.comment, italic = true })
hl(0, "@comment.documentation", { fg = c.comment })
hl(0, "@comment.error", { fg = c.red, bg = c.surface })
hl(0, "@comment.warning", { fg = c.yellow, bg = c.surface })
hl(0, "@comment.todo", { fg = c.black, bg = c.yellow, bold = true })
hl(0, "@comment.note", { fg = c.blue, bg = c.surface })
hl(0, "@markup.strong", { bold = true })
hl(0, "@markup.italic", { italic = true })
hl(0, "@markup.strikethrough", { strikethrough = true })
hl(0, "@markup.underline", { underline = true })
hl(0, "@markup.heading", { fg = c.bright, bold = true })
hl(0, "@markup.quote", { fg = c.comment, italic = true })
hl(0, "@markup.math", { fg = c.cyan })
hl(0, "@markup.link", { fg = c.blue, underline = true })
hl(0, "@markup.link.label", { fg = c.cyan })
hl(0, "@markup.link.url", { fg = c.blue, underline = true })
hl(0, "@markup.raw", { fg = c.green })
hl(0, "@markup.list", { fg = c.bright })
hl(0, "@markup.list.checked", { fg = c.green })
hl(0, "@markup.list.unchecked", { fg = c.dim })
hl(0, "@diff.plus", { fg = c.green })
hl(0, "@diff.minus", { fg = c.red })
hl(0, "@diff.delta", { fg = c.yellow })
hl(0, "@tag", { fg = c.bright })
hl(0, "@tag.attribute", { fg = c.base, italic = true })
hl(0, "@tag.delimiter", { fg = c.dim })

hl(0, "DiagnosticError", { fg = c.red })
hl(0, "DiagnosticWarn", { fg = c.yellow })
hl(0, "DiagnosticInfo", { fg = c.blue })
hl(0, "DiagnosticHint", { fg = c.cyan })
hl(0, "DiagnosticOk", { fg = c.green })
hl(0, "DiagnosticVirtualTextError", { fg = c.red, bg = c.surface })
hl(0, "DiagnosticVirtualTextWarn", { fg = c.yellow, bg = c.surface })
hl(0, "DiagnosticVirtualTextInfo", { fg = c.blue, bg = c.surface })
hl(0, "DiagnosticVirtualTextHint", { fg = c.cyan, bg = c.surface })
hl(0, "DiagnosticVirtualTextOk", { fg = c.green, bg = c.surface })
hl(0, "DiagnosticUnderlineError", { sp = c.red, undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = c.yellow, undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = c.blue, undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = c.cyan, undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = c.green, undercurl = true })
hl(0, "DiagnosticFloatingError", { fg = c.red })
hl(0, "DiagnosticFloatingWarn", { fg = c.yellow })
hl(0, "DiagnosticFloatingInfo", { fg = c.blue })
hl(0, "DiagnosticFloatingHint", { fg = c.cyan })
hl(0, "DiagnosticFloatingOk", { fg = c.green })
hl(0, "DiagnosticSignError", { fg = c.red })
hl(0, "DiagnosticSignWarn", { fg = c.yellow })
hl(0, "DiagnosticSignInfo", { fg = c.blue })
hl(0, "DiagnosticSignHint", { fg = c.cyan })
hl(0, "DiagnosticSignOk", { fg = c.green })
hl(0, "DiagnosticUnnecessary", { fg = c.comment, italic = true })
hl(0, "DiagnosticDeprecated", { strikethrough = true })

hl(0, "LspReferenceText", { bg = c.surface })
hl(0, "LspReferenceRead", { bg = c.surface })
hl(0, "LspReferenceWrite", { bg = c.surface })
hl(0, "LspSignatureActiveParameter", { fg = c.yellow, bold = true })
hl(0, "LspCodeLens", { fg = c.comment })
hl(0, "LspCodeLensSeparator", { fg = c.dim })
hl(0, "LspInlayHint", { fg = c.comment, bg = c.surface, italic = true })

hl(0, "DiffAdd", { fg = c.green, bg = c.surface })
hl(0, "DiffChange", { fg = c.yellow, bg = c.surface })
hl(0, "DiffDelete", { fg = c.red, bg = c.surface })
hl(0, "DiffText", { fg = c.yellow, bg = c.dim, bold = true })
hl(0, "diffAdded", { fg = c.green })
hl(0, "diffRemoved", { fg = c.red })
hl(0, "diffChanged", { fg = c.yellow })
hl(0, "diffFile", { fg = c.bright, bold = true })
hl(0, "diffNewFile", { fg = c.green, bold = true })
hl(0, "diffOldFile", { fg = c.red, bold = true })
hl(0, "diffLine", { fg = c.cyan })
hl(0, "diffIndexLine", { fg = c.magenta })

hl(0, "GitSignsAdd", { fg = c.green })
hl(0, "GitSignsChange", { fg = c.yellow })
hl(0, "GitSignsDelete", { fg = c.red })
hl(0, "GitSignsAddNr", { fg = c.green })
hl(0, "GitSignsChangeNr", { fg = c.yellow })
hl(0, "GitSignsDeleteNr", { fg = c.red })
hl(0, "GitSignsAddLn", { bg = c.surface })
hl(0, "GitSignsChangeLn", { bg = c.surface })
hl(0, "GitSignsDeleteLn", { bg = c.surface })
hl(0, "GitSignsCurrentLineBlame", { fg = c.comment, italic = true })

hl(0, "TelescopeBorder", { fg = c.dim })
hl(0, "TelescopePromptBorder", { fg = c.dim })
hl(0, "TelescopeResultsBorder", { fg = c.dim })
hl(0, "TelescopePreviewBorder", { fg = c.dim })
hl(0, "TelescopePromptNormal", { fg = c.base, bg = c.black })
hl(0, "TelescopeResultsNormal", { fg = c.base, bg = c.black })
hl(0, "TelescopePreviewNormal", { fg = c.base, bg = c.black })
hl(0, "TelescopePromptPrefix", { fg = c.bright })
hl(0, "TelescopePromptTitle", { fg = c.bright, bold = true })
hl(0, "TelescopeResultsTitle", { fg = c.bright, bold = true })
hl(0, "TelescopePreviewTitle", { fg = c.bright, bold = true })
hl(0, "TelescopeSelection", { fg = c.bright, bg = c.surface })
hl(0, "TelescopeSelectionCaret", { fg = c.bright })
hl(0, "TelescopeMatching", { fg = c.yellow, bold = true })

hl(0, "NvimTreeNormal", { fg = c.base, bg = c.black })
hl(0, "NvimTreeNormalNC", { fg = c.base, bg = c.black })
hl(0, "NvimTreeRootFolder", { fg = c.bright, bold = true })
hl(0, "NvimTreeFolderName", { fg = c.blue })
hl(0, "NvimTreeFolderIcon", { fg = c.blue })
hl(0, "NvimTreeOpenedFolderName", { fg = c.blue_bright })
hl(0, "NvimTreeEmptyFolderName", { fg = c.comment })
hl(0, "NvimTreeSymlink", { fg = c.cyan })
hl(0, "NvimTreeExecFile", { fg = c.green, bold = true })
hl(0, "NvimTreeSpecialFile", { fg = c.magenta })
hl(0, "NvimTreeImageFile", { fg = c.magenta })
hl(0, "NvimTreeIndentMarker", { fg = c.dim })
hl(0, "NvimTreeGitDirty", { fg = c.yellow })
hl(0, "NvimTreeGitStaged", { fg = c.green })
hl(0, "NvimTreeGitMerge", { fg = c.magenta })
hl(0, "NvimTreeGitRenamed", { fg = c.cyan })
hl(0, "NvimTreeGitNew", { fg = c.green })
hl(0, "NvimTreeGitDeleted", { fg = c.red })

hl(0, "LazyNormal", { fg = c.base, bg = c.black })
hl(0, "LazyButton", { fg = c.base, bg = c.surface })
hl(0, "LazyButtonActive", { fg = c.black, bg = c.base })
hl(0, "LazyH1", { fg = c.black, bg = c.bright, bold = true })
hl(0, "LazyH2", { fg = c.bright, bold = true })
hl(0, "LazySpecial", { fg = c.cyan })
hl(0, "LazyProgressDone", { fg = c.green })
hl(0, "LazyProgressTodo", { fg = c.dim })

hl(0, "CmpItemAbbr", { fg = c.base })
hl(0, "CmpItemAbbrDeprecated", { fg = c.comment, strikethrough = true })
hl(0, "CmpItemAbbrMatch", { fg = c.bright, bold = true })
hl(0, "CmpItemAbbrMatchFuzzy", { fg = c.bright })
hl(0, "CmpItemKind", { fg = c.magenta })
hl(0, "CmpItemKindClass", { fg = c.yellow })
hl(0, "CmpItemKindColor", { fg = c.magenta })
hl(0, "CmpItemKindConstant", { fg = c.bright })
hl(0, "CmpItemKindConstructor", { fg = c.yellow })
hl(0, "CmpItemKindEnum", { fg = c.yellow })
hl(0, "CmpItemKindEnumMember", { fg = c.bright })
hl(0, "CmpItemKindEvent", { fg = c.magenta })
hl(0, "CmpItemKindField", { fg = c.base })
hl(0, "CmpItemKindFile", { fg = c.blue })
hl(0, "CmpItemKindFolder", { fg = c.blue })
hl(0, "CmpItemKindFunction", { fg = c.bright })
hl(0, "CmpItemKindInterface", { fg = c.yellow })
hl(0, "CmpItemKindKeyword", { fg = c.bright })
hl(0, "CmpItemKindMethod", { fg = c.bright })
hl(0, "CmpItemKindModule", { fg = c.base })
hl(0, "CmpItemKindOperator", { fg = c.base })
hl(0, "CmpItemKindProperty", { fg = c.base })
hl(0, "CmpItemKindReference", { fg = c.base })
hl(0, "CmpItemKindSnippet", { fg = c.green })
hl(0, "CmpItemKindStruct", { fg = c.yellow })
hl(0, "CmpItemKindText", { fg = c.comment })
hl(0, "CmpItemKindTypeParameter", { fg = c.yellow })
hl(0, "CmpItemKindUnit", { fg = c.magenta })
hl(0, "CmpItemKindValue", { fg = c.bright })
hl(0, "CmpItemKindVariable", { fg = c.base })
hl(0, "CmpItemMenu", { fg = c.comment })

hl(0, "IndentBlanklineChar", { fg = c.surface })
hl(0, "IndentBlanklineContextChar", { fg = c.dim })
hl(0, "IblIndent", { fg = c.surface })
hl(0, "IblScope", { fg = c.dim })

hl(0, "RainbowDelimiterRed", { fg = c.red })
hl(0, "RainbowDelimiterYellow", { fg = c.yellow })
hl(0, "RainbowDelimiterBlue", { fg = c.blue })
hl(0, "RainbowDelimiterOrange", { fg = c.bright })
hl(0, "RainbowDelimiterGreen", { fg = c.green })
hl(0, "RainbowDelimiterViolet", { fg = c.magenta })
hl(0, "RainbowDelimiterCyan", { fg = c.cyan })

hl(0, "NotifyERRORBorder", { fg = c.red })
hl(0, "NotifyERRORIcon", { fg = c.red })
hl(0, "NotifyERRORTitle", { fg = c.red, bold = true })
hl(0, "NotifyWARNBorder", { fg = c.yellow })
hl(0, "NotifyWARNIcon", { fg = c.yellow })
hl(0, "NotifyWARNTitle", { fg = c.yellow, bold = true })
hl(0, "NotifyINFOBorder", { fg = c.blue })
hl(0, "NotifyINFOIcon", { fg = c.blue })
hl(0, "NotifyINFOTitle", { fg = c.blue, bold = true })
hl(0, "NotifyDEBUGBorder", { fg = c.comment })
hl(0, "NotifyDEBUGIcon", { fg = c.comment })
hl(0, "NotifyDEBUGTitle", { fg = c.comment, bold = true })
hl(0, "NotifyTRACEBorder", { fg = c.magenta })
hl(0, "NotifyTRACEIcon", { fg = c.magenta })
hl(0, "NotifyTRACETitle", { fg = c.magenta, bold = true })
hl(0, "NotifyBackground", { bg = c.black })

hl(0, "WhichKey", { fg = c.bright })
hl(0, "WhichKeyGroup", { fg = c.cyan })
hl(0, "WhichKeyDesc", { fg = c.base })
hl(0, "WhichKeySeparator", { fg = c.dim })
hl(0, "WhichKeyFloat", { bg = c.black })
hl(0, "WhichKeyBorder", { fg = c.dim })
hl(0, "WhichKeyValue", { fg = c.comment })

hl(0, "MasonNormal", { fg = c.base, bg = c.black })
hl(0, "MasonHeader", { fg = c.black, bg = c.bright, bold = true })
hl(0, "MasonHeaderSecondary", { fg = c.black, bg = c.blue, bold = true })
hl(0, "MasonHighlight", { fg = c.cyan })
hl(0, "MasonHighlightBlock", { fg = c.black, bg = c.cyan })
hl(0, "MasonHighlightBlockBold", { fg = c.black, bg = c.cyan, bold = true })
hl(0, "MasonMuted", { fg = c.comment })
hl(0, "MasonMutedBlock", { fg = c.black, bg = c.comment })

hl(0, "healthError", { fg = c.red })
hl(0, "healthSuccess", { fg = c.green })
hl(0, "healthWarning", { fg = c.yellow })

hl(0, "lualine_a_normal", { fg = c.black, bg = c.base, bold = true })
hl(0, "lualine_b_normal", { fg = c.base, bg = c.surface })
hl(0, "lualine_c_normal", { fg = c.base, bg = c.surface })
hl(0, "lualine_a_insert", { fg = c.black, bg = c.bright, bold = true })
hl(0, "lualine_b_insert", { fg = c.bright, bg = c.surface })
hl(0, "lualine_c_insert", { fg = c.base, bg = c.surface })
hl(0, "lualine_a_visual", { fg = c.black, bg = c.yellow, bold = true })
hl(0, "lualine_b_visual", { fg = c.yellow, bg = c.surface })
hl(0, "lualine_c_visual", { fg = c.base, bg = c.surface })
hl(0, "lualine_a_replace", { fg = c.black, bg = c.red, bold = true })
hl(0, "lualine_b_replace", { fg = c.red, bg = c.surface })
hl(0, "lualine_c_replace", { fg = c.base, bg = c.surface })
hl(0, "lualine_a_command", { fg = c.black, bg = c.cyan, bold = true })
hl(0, "lualine_b_command", { fg = c.cyan, bg = c.surface })
hl(0, "lualine_c_command", { fg = c.base, bg = c.surface })
hl(0, "lualine_a_inactive", { fg = c.comment, bg = c.surface })
hl(0, "lualine_b_inactive", { fg = c.comment, bg = c.surface })
hl(0, "lualine_c_inactive", { fg = c.comment, bg = c.surface })

return { colors = c }
